// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using KinopoiskNET.Core.DTO;
//
//    var movieInfo = MovieInfo.FromJson(jsonString);

namespace KinopoiskNET.Core.DTO
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;

    using KinopoiskNET.Core.DTO.Converters;

    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class MovieInfo
    {
        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("id_kinopoisk")]
        public long IdKinopoisk { get; set; }

        [JsonProperty("url")]
        public string Url { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("title_alternative")]
        public string TitleAlternative { get; set; }

        [JsonProperty("tagline")]
        public string Tagline { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }

        [JsonProperty("year")]
        public long Year { get; set; }

        [JsonProperty("poster")]
        public string Poster { get; set; }

        [JsonProperty("trailer")]
        public Uri Trailer { get; set; }

        [JsonProperty("age")]
        public string Age { get; set; }

        [JsonProperty("actors")]
        public List<string> Actors { get; set; }

        [JsonProperty("countries")]
        public List<string> Countries { get; set; }

        [JsonProperty("genres")]
        public List<string> Genres { get; set; }

        [JsonProperty("directors")]
        public List<string> Directors { get; set; }

        [JsonProperty("screenwriters")]
        public List<string> Screenwriters { get; set; }

        [JsonProperty("producers")]
        public List<string> Producers { get; set; }

        [JsonProperty("operators")]
        public List<string> Operators { get; set; }

        [JsonProperty("composers")]
        public List<string> Composers { get; set; }

        [JsonProperty("painters")]
        public List<string> Painters { get; set; }

        [JsonProperty("editors")]
        public List<string> Editors { get; set; }

        [JsonProperty("budget")]
        public object Budget { get; set; }

        [JsonProperty("rating_kinopoisk")]
        public double RatingKinopoisk { get; set; }

        [JsonProperty("rating_imdb")]
        public double RatingImdb { get; set; }

        [JsonProperty("kinopoisk_votes")]
        public object KinopoiskVotes { get; set; }

        [JsonProperty("imdb_votes")]
        public object ImdbVotes { get; set; }

        [JsonProperty("fees_world")]
        public string FeesWorld { get; set; }

        [JsonProperty("fees_russia")]
        public object FeesRussia { get; set; }

        [JsonProperty("premiere_world")]
        public string PremiereWorld { get; set; }

        [JsonProperty("premiere_russia")]
        public string PremiereRussia { get; set; }

        [JsonProperty("frames")]
        public List<Uri> Frames { get; set; }

        [JsonProperty("screenshots")]
        public object Screenshots { get; set; }

        [JsonProperty("videocdn")]
        public MovieCollapse Videocdn { get; set; }

        [JsonProperty("hdvb")]
        public MovieCollapse Hdvb { get; set; }

        [JsonProperty("collapse")]
        public MovieCollapse Collapse { get; set; }

        [JsonProperty("kodik")]
        public MovieCollapse Kodik { get; set; }
    }

    public partial class MovieCollapse
    {
        [JsonProperty("url")]
        public List<string> Url { get; set; }

        [JsonProperty("quality")]
        public List<string> Quality { get; set; }

        [JsonProperty("duration")]
        public List<string> Duration { get; set; }

        [JsonProperty("voice")]
        public List<string> Voice { get; set; }
    }

    public partial class MovieInfo
    {
        public static MovieInfo FromJson(string json) => JsonConvert.DeserializeObject<MovieInfo>(json, Converter.Settings);
    }

    public static partial class Serialize
    {
        public static string ToJson(this MovieInfo self) => JsonConvert.SerializeObject(self, Converter.Settings);
    }
}
