// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using KinopoiskNET.Core.DTO;
//
//    var tvSeriesInfo = TvSeriesInfo.FromJson(jsonString);

namespace KinopoiskNET.Core.DTO
{
    using KinopoiskNET.Core.DTO.Converters;

    using Newtonsoft.Json;

    using System;
    using System.Collections.Generic;

    public partial class TvSeriesInfo
    {
        [JsonProperty("id")]
        [JsonConverter(typeof(LongConverter))]
        public long Id { get; set; }

        [JsonProperty("id_kinopoisk")]
        [JsonConverter(typeof(LongConverter))]
        public long IdKinopoisk { get; set; }

        [JsonProperty("url")]
        public string Url { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("title_alternative")]
        public object TitleAlternative { get; set; }

        [JsonProperty("tagline")]
        public object Tagline { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }

        [JsonProperty("year")]
        public long Year { get; set; }

        [JsonProperty("poster")]
        public string Poster { get; set; }

        [JsonProperty("trailer")]
        public Uri Trailer { get; set; }

        [JsonProperty("age")]
        public string Age { get; set; }

        [JsonProperty("actors")]
        public List<string> Actors { get; set; }

        [JsonProperty("countries")]
        public List<string> Countries { get; set; }

        [JsonProperty("genres")]
        public List<string> Genres { get; set; }

        [JsonProperty("directors")]
        public List<string> Directors { get; set; }

        [JsonProperty("screenwriters")]
        public List<string> Screenwriters { get; set; }

        [JsonProperty("producers")]
        public object Producers { get; set; }

        [JsonProperty("operators")]
        public List<string> Operators { get; set; }

        [JsonProperty("composers")]
        public List<string> Composers { get; set; }

        [JsonProperty("painters")]
        public List<string> Painters { get; set; }

        [JsonProperty("editors")]
        public List<string> Editors { get; set; }

        [JsonProperty("budget")]
        public object Budget { get; set; }

        [JsonProperty("rating_kinopoisk")]
        [JsonConverter(typeof(LongConverter))]
        public long RatingKinopoisk { get; set; }

        [JsonProperty("rating_imdb")]
        public string RatingImdb { get; set; }

        [JsonProperty("kinopoisk_votes")]
        public object KinopoiskVotes { get; set; }

        [JsonProperty("imdb_votes")]
        public object ImdbVotes { get; set; }

        [JsonProperty("fees_world")]
        public object FeesWorld { get; set; }

        [JsonProperty("fees_russia")]
        public object FeesRussia { get; set; }

        [JsonProperty("premiere_world")]
        public string PremiereWorld { get; set; }

        [JsonProperty("premiere_russia")]
        public object PremiereRussia { get; set; }

        [JsonProperty("frames")]
        public List<Uri> Frames { get; set; }

        [JsonProperty("screenshots")]
        public List<Uri> Screenshots { get; set; }

        [JsonProperty("seasons")]
        public long Seasons { get; set; }

        [JsonProperty("videocdn")]
        public TvSeriesCollapse Videocdn { get; set; }

        [JsonProperty("hdvb")]
        public TvSeriesCollapse Hdvb { get; set; }

        [JsonProperty("collapse")]
        public TvSeriesCollapse Collapse { get; set; }

        [JsonProperty("kodik")]
        public TvSeriesCollapse Kodik { get; set; }
    }

    public partial class TvSeriesCollapse
    {
        [JsonProperty("url")]
        public List<string> Url { get; set; }

        [JsonProperty("quality")]
        public List<string> Quality { get; set; }

        [JsonProperty("duration")]
        public List<string> Duration { get; set; }

        [JsonProperty("voice")]
        public List<string> Voice { get; set; }

        [JsonProperty("seasons")]
        public object Seasons { get; set; }

        [JsonProperty("episodes")]
        public object Episodes { get; set; }
    }

    public partial class TvSeriesInfo
    {
        public static TvSeriesInfo FromJson(string json) => JsonConvert.DeserializeObject<TvSeriesInfo>(json, Converter.Settings);
    }

    public static partial class Serialize
    {
        public static string ToJson(this TvSeriesInfo self) => JsonConvert.SerializeObject(self, Converter.Settings);
    }
}
